version: "3.5"
services:
  mrtg:
    image: fboaventura/dckr-mrtg:v2.2.0
    #    build: .
    hostname: mrtg
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./conf.d:/etc/mrtg/conf.d"
      - "./html:/mrtg/html"
    environment:
      TZ: "Europe/Istanbul"
      HOSTS: "public:localhost"
      WEBDIR: "/mrtg/html"
    tmpfs:
      - "/run"